title: Predictive Brain Lab Wiki
logo: /images/pred-lab-logo.png
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
